[package]
name = "mamba-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ndarray = {version = "0.13", features = ["blas"]}
ndarray-linalg = {version = "0.12", optional = true, default-features = false}
ndarray-stats = "0.3"
ndarray-rand = "0.11"
rand = "0.7"